# Nawaloka Crawler Configuration
crawler:
  base_url: "your URL"
  max_depth: 3 #configure your required depth
  request_delay: 2.0 #configure your required delay between requests in seconds

  #your routes to start crawling from
  start_paths:
    - "/"
    - "/our-centres"
    - "/healthchecks"
    - "/channeling"
    - "/aboutus"
    - "/contactus"
    - "/blogs-and-news"
  #your routes to exclude from crawling
  exclude_patterns:
    - "/login"
    - "/terms"
    - "/privacy"
    - "/admin"
    - "/images/"
    - "/downloads/"
    - "/media/"
